version: '3.7'
services:
  reservation_api:
    container_name: reservation_api
    build: .
    networks:
      - reservation_api_local_network
    ports:
      - "3333:3333"
    volumes:
      - ./src:/reservation-api/src
  mysql:
    platform: linux/x86_64
    image: mysql:8.0.19
    restart: always
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - "3306"
    networks:
      reservation_api_local_network:
        aliases:
          - mysql
    volumes:
      - ./reservation-db:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
networks:
  reservation_api_local_network:
    external: true
