version: '2.4'
services:
  reservation_api:
    container_name: reservation_api
    build: .
    networks:
      - reservation_api_local_network
    ports:
      - "3333:3333"
    volumes:
      - ./src:/reservation-api/src
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "node" ,"./healthcheck.js" ]
      start_period: 1s
      timeout: 5s
      retries: 10
  mysql:
    container_name: reservation_mysql
    platform: linux/x86_64
    image: mysql:8.0.19
    restart: always
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - "3306"
    networks:
      reservation_api_local_network:
        aliases:
          - mysql
    volumes:
      - ./reservation-db:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
networks:
  reservation_api_local_network:
    external: true
